FILES = Code/source/main.c Code/source/in_game.c Code/source/pre_game.c Code/source/solver.c Code/source/solver_chance_method.c Code/source/solver_helper.c Code/source/solver_mark_method.c
TARGET = minesweeper

all: build

build:
	gcc $(FILES) -o $(TARGET) -std=c99

clean:
	rm $(TARGET)
